### ISSUE TITLE
TypeError: coercing to Unicode: need string or buffer, list found

### ISSUE THREAD

**Issue by markorapaic** [samarjeet27/CSV-Mapper#4]
Hello,

I'm having trouble getting a simple test to work - i've attached examples of the python script and an associated csv document - what do you think could be causing the TypeError? I've also included the Traceback below:

Python Script
```python
import csvmapper

mapper = csvmapper.JSONMapper([
  [
    {'name':'email'},
    {'name':'firstname'},
    {'name':'lastname'},
    {'name':'website'},
    {'name':'company'},
    {'name':'phone'},
    {'name':'address'},
    {'name':'city'},
    {'name':'state'},
    {'name':'zip', 'type':'int'}
  ]
])

parser = csvmapper.CSVParser('contact.csv', mapper)
payload = csvmapper.JSONConverter(parser).doConvert(pretty=False)

print payload
```

CSV document
```csv
email,marko@python.com.au
firstname,Monty
lastname,Python
website,http://www.python.org
company,Python
phone,555-122-2323
address,1 Shrubbery Lane
city,London
state,PY
zip,31415
```

Traceback:
```shell
Traceback (most recent call last):
  File "test_2.py", line 14, in <module>
    {'name':'zip', 'type':'int'}
  File "/Library/Python/2.7/site-packages/csvmapper/mapper.py", line 59, in __init__
    super(JSONMapper, self).__init__(self.parse(jsonFile))
  File "/Library/Python/2.7/site-packages/csvmapper/mapper.py", line 62, in parse
    fs = open(jFile)
TypeError: coercing to Unicode: need string or buffer, list found
```

**Comment by samarjeet27** [comment]
Hi,
Thanks for showing interest.
Please use DictMapper instead of JSONMapper. As JSONMapper reads the mapper from a JSON file.
Also, the CSV file is not structured properly.CSV-Mapper eliminates the need for specifying row headers.
So, you don't need to use email,first name etc.
And the data should be structured in a tabular kind of form.
So, it the csv file would be like -

```
marko@python.com.au,Monty,Python,http://www.python.org,Python,555-122-2323,1 Shrubbery Lane,London,PY,31415
```

You can also retain the headers in the CSV file
For example the following file -
```
email,firstname,lastname,website,company,phone,address,city,state,zip
marko@python.com.au,Monty,Python,http://www.python.org,Python,555-122-2323,1 Shrubbery Lane,London,PY,31415
```
Could be parsed without a mapper because it already has header information.

```python
parser = csvmapper.CSVParser('contact.csv', hasHeader=True)
```

**Comment by samarjeet27** [comment]
@markorapaic is it working now ?
